remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
title: Awesome Full Stack
description: Take a small step towards a full stack developer.
show_downloads: false
google_analytics: ""